apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-product
  labels:
    app: ms-product
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-product
  template:
    metadata:
      labels:
        app: ms-product
    spec:
      containers:
        - name: ms-product
          image: 011706314791.dkr.ecr.ca-central-1.amazonaws.com/meli-challenge/ms-product:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
      imagePullSecrets:
        - name: ecr-secret
