apiVersion: v1
kind: Service
metadata:
  name: ms-product-service
  labels:
    app: ms-product
spec:
  selector:
    app: ms-product
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
